### ISSUE TITLE
line message, address = server_socket.recvfrom(1024) just hangs for me

### ISSUE THREAD

**Issue by caseybentz8** [nettrom/forza_motorsport#8]
Edit: I got it to work by allowing python.exe to use private and public in the allow apps to communicate through windows defender firewall.

I have been messing around with this all afternoon and I cannot get the script to write any data from my xbox to my laptop on the same network. I have configured the settings on the xbox with the ip address of my laptop and the port suggested here (as well as a few others). At this point I do not know what to do.

**Comment by nettrom** [comment]
Hi, thanks for asking about this! Sorry I didn't get to it before you got it figured out. It's useful to know that firewall rules might specifically block the packets from getting through and that a specific rule might need to be set. I hope the library works as it should from now on, and please get in touch again if something breaks.
